/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
import * as reactQuery from "@tanstack/react-query";
import {
  type NeurachatContext,
  useNeurachatContext,
  queryKeyFn,
} from "./neurachatContext";
import { deepMerge } from "./neurachatUtils";
import type * as Fetcher from "./neurachatFetcher";
import { neurachatFetch } from "./neurachatFetcher";
import type * as Schemas from "./neurachatSchemas";

type QueryFnOptions = {
  signal?: AbortController["signal"];
};

export type AppControllerGetHealthCheckError = Fetcher.ErrorWrapper<undefined>;

export type AppControllerGetHealthCheckVariables =
  NeurachatContext["fetcherOptions"];

export const fetchAppControllerGetHealthCheck = (
  variables: AppControllerGetHealthCheckVariables,
  signal?: AbortSignal,
) =>
  neurachatFetch<
    Schemas.NoResponseDataDto,
    AppControllerGetHealthCheckError,
    undefined,
    {},
    {},
    {}
  >({ url: "/health-check", method: "get", ...variables, signal });

export function appControllerGetHealthCheckQuery(
  variables: AppControllerGetHealthCheckVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.NoResponseDataDto>;
};

export function appControllerGetHealthCheckQuery(
  variables: AppControllerGetHealthCheckVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.NoResponseDataDto>)
    | reactQuery.SkipToken;
};

export function appControllerGetHealthCheckQuery(
  variables: AppControllerGetHealthCheckVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/health-check",
      operationId: "appControllerGetHealthCheck",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchAppControllerGetHealthCheck(variables, signal),
  };
}

export const useSuspenseAppControllerGetHealthCheck = <
  TData = Schemas.NoResponseDataDto,
>(
  variables: AppControllerGetHealthCheckVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.NoResponseDataDto,
      AppControllerGetHealthCheckError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useNeurachatContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.NoResponseDataDto,
    AppControllerGetHealthCheckError,
    TData
  >({
    ...appControllerGetHealthCheckQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useAppControllerGetHealthCheck = <
  TData = Schemas.NoResponseDataDto,
>(
  variables: AppControllerGetHealthCheckVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.NoResponseDataDto,
      AppControllerGetHealthCheckError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useNeurachatContext(options);
  return reactQuery.useQuery<
    Schemas.NoResponseDataDto,
    AppControllerGetHealthCheckError,
    TData
  >({
    ...appControllerGetHealthCheckQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type AppControllerGetRootError = Fetcher.ErrorWrapper<undefined>;

export type AppControllerGetRootVariables = NeurachatContext["fetcherOptions"];

export const fetchAppControllerGetRoot = (
  variables: AppControllerGetRootVariables,
  signal?: AbortSignal,
) =>
  neurachatFetch<
    Schemas.NoResponseDataDto,
    AppControllerGetRootError,
    undefined,
    {},
    {},
    {}
  >({ url: "/", method: "get", ...variables, signal });

export function appControllerGetRootQuery(
  variables: AppControllerGetRootVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.NoResponseDataDto>;
};

export function appControllerGetRootQuery(
  variables: AppControllerGetRootVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.NoResponseDataDto>)
    | reactQuery.SkipToken;
};

export function appControllerGetRootQuery(
  variables: AppControllerGetRootVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/",
      operationId: "appControllerGetRoot",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchAppControllerGetRoot(variables, signal),
  };
}

export const useSuspenseAppControllerGetRoot = <
  TData = Schemas.NoResponseDataDto,
>(
  variables: AppControllerGetRootVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.NoResponseDataDto,
      AppControllerGetRootError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useNeurachatContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.NoResponseDataDto,
    AppControllerGetRootError,
    TData
  >({
    ...appControllerGetRootQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useAppControllerGetRoot = <TData = Schemas.NoResponseDataDto>(
  variables: AppControllerGetRootVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.NoResponseDataDto,
      AppControllerGetRootError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useNeurachatContext(options);
  return reactQuery.useQuery<
    Schemas.NoResponseDataDto,
    AppControllerGetRootError,
    TData
  >({
    ...appControllerGetRootQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type AuthControllerRegisterError = Fetcher.ErrorWrapper<
  | {
      status: 403;
      payload: Schemas.ExceptionDto;
    }
  | {
      status: 409;
      payload: Schemas.ExceptionDto;
    }
>;

export type AuthControllerRegisterVariables = {
  body: Schemas.RegisterRequest;
} & NeurachatContext["fetcherOptions"];

/**
 * Register a new user
 */
export const fetchAuthControllerRegister = (
  variables: AuthControllerRegisterVariables,
  signal?: AbortSignal,
) =>
  neurachatFetch<
    Schemas.NoResponseDataDto,
    AuthControllerRegisterError,
    Schemas.RegisterRequest,
    {},
    {},
    {}
  >({ url: "/auth/register", method: "post", ...variables, signal });

/**
 * Register a new user
 */
export const useAuthControllerRegister = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.NoResponseDataDto,
      AuthControllerRegisterError,
      AuthControllerRegisterVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useNeurachatContext();
  return reactQuery.useMutation<
    Schemas.NoResponseDataDto,
    AuthControllerRegisterError,
    AuthControllerRegisterVariables
  >({
    mutationFn: (variables: AuthControllerRegisterVariables) =>
      fetchAuthControllerRegister(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type AuthControllerConfirmEmailPathParams = {
  /**
   * Token to confirm email
   */
  token: string;
};

export type AuthControllerConfirmEmailError = Fetcher.ErrorWrapper<{
  status: 400;
  payload: Schemas.ExceptionDto;
}>;

export type AuthControllerConfirmEmailVariables = {
  pathParams: AuthControllerConfirmEmailPathParams;
} & NeurachatContext["fetcherOptions"];

/**
 * Confirm user email using token
 */
export const fetchAuthControllerConfirmEmail = (
  variables: AuthControllerConfirmEmailVariables,
  signal?: AbortSignal,
) =>
  neurachatFetch<
    Schemas.NoResponseDataDto,
    AuthControllerConfirmEmailError,
    undefined,
    {},
    {},
    AuthControllerConfirmEmailPathParams
  >({
    url: "/auth/confirm-email/{token}",
    method: "get",
    ...variables,
    signal,
  });

/**
 * Confirm user email using token
 */
export function authControllerConfirmEmailQuery(
  variables: AuthControllerConfirmEmailVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.NoResponseDataDto>;
};

export function authControllerConfirmEmailQuery(
  variables: AuthControllerConfirmEmailVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.NoResponseDataDto>)
    | reactQuery.SkipToken;
};

export function authControllerConfirmEmailQuery(
  variables: AuthControllerConfirmEmailVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/auth/confirm-email/{token}",
      operationId: "authControllerConfirmEmail",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchAuthControllerConfirmEmail(variables, signal),
  };
}

/**
 * Confirm user email using token
 */
export const useSuspenseAuthControllerConfirmEmail = <
  TData = Schemas.NoResponseDataDto,
>(
  variables: AuthControllerConfirmEmailVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.NoResponseDataDto,
      AuthControllerConfirmEmailError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useNeurachatContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.NoResponseDataDto,
    AuthControllerConfirmEmailError,
    TData
  >({
    ...authControllerConfirmEmailQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * Confirm user email using token
 */
export const useAuthControllerConfirmEmail = <
  TData = Schemas.NoResponseDataDto,
>(
  variables: AuthControllerConfirmEmailVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.NoResponseDataDto,
      AuthControllerConfirmEmailError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useNeurachatContext(options);
  return reactQuery.useQuery<
    Schemas.NoResponseDataDto,
    AuthControllerConfirmEmailError,
    TData
  >({
    ...authControllerConfirmEmailQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type AuthControllerLoginError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.ExceptionDto;
    }
  | {
      status: 403;
      payload: Schemas.ExceptionDto;
    }
>;

export type AuthControllerLoginVariables = {
  body: Schemas.LoginRequest;
} & NeurachatContext["fetcherOptions"];

/**
 * Login user and return access and refresh tokens
 */
export const fetchAuthControllerLogin = (
  variables: AuthControllerLoginVariables,
  signal?: AbortSignal,
) =>
  neurachatFetch<
    Schemas.LoginResponse,
    AuthControllerLoginError,
    Schemas.LoginRequest,
    {},
    {},
    {}
  >({ url: "/auth/login", method: "post", ...variables, signal });

/**
 * Login user and return access and refresh tokens
 */
export const useAuthControllerLogin = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.LoginResponse,
      AuthControllerLoginError,
      AuthControllerLoginVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useNeurachatContext();
  return reactQuery.useMutation<
    Schemas.LoginResponse,
    AuthControllerLoginError,
    AuthControllerLoginVariables
  >({
    mutationFn: (variables: AuthControllerLoginVariables) =>
      fetchAuthControllerLogin(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type AuthControllerRefreshTokenError = Fetcher.ErrorWrapper<{
  status: 400;
  payload: Schemas.ExceptionDto;
}>;

export type AuthControllerRefreshTokenVariables =
  NeurachatContext["fetcherOptions"];

/**
 * Refresh access and refresh tokens using refresh token
 */
export const fetchAuthControllerRefreshToken = (
  variables: AuthControllerRefreshTokenVariables,
  signal?: AbortSignal,
) =>
  neurachatFetch<
    Schemas.LoginResponse,
    AuthControllerRefreshTokenError,
    undefined,
    {},
    {},
    {}
  >({ url: "/auth/refresh-token", method: "post", ...variables, signal });

/**
 * Refresh access and refresh tokens using refresh token
 */
export const useAuthControllerRefreshToken = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.LoginResponse,
      AuthControllerRefreshTokenError,
      AuthControllerRefreshTokenVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useNeurachatContext();
  return reactQuery.useMutation<
    Schemas.LoginResponse,
    AuthControllerRefreshTokenError,
    AuthControllerRefreshTokenVariables
  >({
    mutationFn: (variables: AuthControllerRefreshTokenVariables) =>
      fetchAuthControllerRefreshToken(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type AuthControllerForgotPasswordError = Fetcher.ErrorWrapper<{
  status: 400;
  payload: Schemas.ExceptionDto;
}>;

export type AuthControllerForgotPasswordVariables = {
  body: Schemas.ForgotPasswordRequest;
} & NeurachatContext["fetcherOptions"];

/**
 * Send password reset link to user email
 */
export const fetchAuthControllerForgotPassword = (
  variables: AuthControllerForgotPasswordVariables,
  signal?: AbortSignal,
) =>
  neurachatFetch<
    Schemas.NoResponseDataDto,
    AuthControllerForgotPasswordError,
    Schemas.ForgotPasswordRequest,
    {},
    {},
    {}
  >({ url: "/auth/forgot-password", method: "post", ...variables, signal });

/**
 * Send password reset link to user email
 */
export const useAuthControllerForgotPassword = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.NoResponseDataDto,
      AuthControllerForgotPasswordError,
      AuthControllerForgotPasswordVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useNeurachatContext();
  return reactQuery.useMutation<
    Schemas.NoResponseDataDto,
    AuthControllerForgotPasswordError,
    AuthControllerForgotPasswordVariables
  >({
    mutationFn: (variables: AuthControllerForgotPasswordVariables) =>
      fetchAuthControllerForgotPassword(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type AuthControllerResetPasswordError = Fetcher.ErrorWrapper<{
  status: 400;
  payload: Schemas.ExceptionDto;
}>;

export type AuthControllerResetPasswordVariables = {
  body: Schemas.ResetPasswordRequest;
} & NeurachatContext["fetcherOptions"];

/**
 * Reset user password using token
 */
export const fetchAuthControllerResetPassword = (
  variables: AuthControllerResetPasswordVariables,
  signal?: AbortSignal,
) =>
  neurachatFetch<
    Schemas.NoResponseDataDto,
    AuthControllerResetPasswordError,
    Schemas.ResetPasswordRequest,
    {},
    {},
    {}
  >({ url: "/auth/reset-password", method: "post", ...variables, signal });

/**
 * Reset user password using token
 */
export const useAuthControllerResetPassword = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.NoResponseDataDto,
      AuthControllerResetPasswordError,
      AuthControllerResetPasswordVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useNeurachatContext();
  return reactQuery.useMutation<
    Schemas.NoResponseDataDto,
    AuthControllerResetPasswordError,
    AuthControllerResetPasswordVariables
  >({
    mutationFn: (variables: AuthControllerResetPasswordVariables) =>
      fetchAuthControllerResetPassword(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type AuthControllerLogoutError = Fetcher.ErrorWrapper<undefined>;

export type AuthControllerLogoutVariables = NeurachatContext["fetcherOptions"];

export const fetchAuthControllerLogout = (
  variables: AuthControllerLogoutVariables,
  signal?: AbortSignal,
) =>
  neurachatFetch<undefined, AuthControllerLogoutError, undefined, {}, {}, {}>({
    url: "/auth/logout",
    method: "post",
    ...variables,
    signal,
  });

export const useAuthControllerLogout = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      AuthControllerLogoutError,
      AuthControllerLogoutVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useNeurachatContext();
  return reactQuery.useMutation<
    undefined,
    AuthControllerLogoutError,
    AuthControllerLogoutVariables
  >({
    mutationFn: (variables: AuthControllerLogoutVariables) =>
      fetchAuthControllerLogout(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type UtilsControllerCheckUsernameUniquenessPathParams = {
  username: string;
};

export type UtilsControllerCheckUsernameUniquenessError = Fetcher.ErrorWrapper<{
  status: 502;
  payload: Schemas.ExceptionDto;
}>;

export type UtilsControllerCheckUsernameUniquenessVariables = {
  pathParams: UtilsControllerCheckUsernameUniquenessPathParams;
} & NeurachatContext["fetcherOptions"];

/**
 * Check if the username is available
 */
export const fetchUtilsControllerCheckUsernameUniqueness = (
  variables: UtilsControllerCheckUsernameUniquenessVariables,
  signal?: AbortSignal,
) =>
  neurachatFetch<
    Schemas.NoResponseDataDto,
    UtilsControllerCheckUsernameUniquenessError,
    undefined,
    {},
    {},
    UtilsControllerCheckUsernameUniquenessPathParams
  >({ url: "/utils/username/{username}", method: "get", ...variables, signal });

/**
 * Check if the username is available
 */
export function utilsControllerCheckUsernameUniquenessQuery(
  variables: UtilsControllerCheckUsernameUniquenessVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.NoResponseDataDto>;
};

export function utilsControllerCheckUsernameUniquenessQuery(
  variables:
    | UtilsControllerCheckUsernameUniquenessVariables
    | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.NoResponseDataDto>)
    | reactQuery.SkipToken;
};

export function utilsControllerCheckUsernameUniquenessQuery(
  variables:
    | UtilsControllerCheckUsernameUniquenessVariables
    | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/utils/username/{username}",
      operationId: "utilsControllerCheckUsernameUniqueness",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchUtilsControllerCheckUsernameUniqueness(variables, signal),
  };
}

/**
 * Check if the username is available
 */
export const useSuspenseUtilsControllerCheckUsernameUniqueness = <
  TData = Schemas.NoResponseDataDto,
>(
  variables: UtilsControllerCheckUsernameUniquenessVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.NoResponseDataDto,
      UtilsControllerCheckUsernameUniquenessError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useNeurachatContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.NoResponseDataDto,
    UtilsControllerCheckUsernameUniquenessError,
    TData
  >({
    ...utilsControllerCheckUsernameUniquenessQuery(
      deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

/**
 * Check if the username is available
 */
export const useUtilsControllerCheckUsernameUniqueness = <
  TData = Schemas.NoResponseDataDto,
>(
  variables:
    | UtilsControllerCheckUsernameUniquenessVariables
    | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.NoResponseDataDto,
      UtilsControllerCheckUsernameUniquenessError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useNeurachatContext(options);
  return reactQuery.useQuery<
    Schemas.NoResponseDataDto,
    UtilsControllerCheckUsernameUniquenessError,
    TData
  >({
    ...utilsControllerCheckUsernameUniquenessQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type UserControllerGetCurrentUserError = Fetcher.ErrorWrapper<undefined>;

export type UserControllerGetCurrentUserVariables =
  NeurachatContext["fetcherOptions"];

/**
 * Get current user profile
 */
export const fetchUserControllerGetCurrentUser = (
  variables: UserControllerGetCurrentUserVariables,
  signal?: AbortSignal,
) =>
  neurachatFetch<
    undefined,
    UserControllerGetCurrentUserError,
    undefined,
    {},
    {},
    {}
  >({ url: "/user", method: "get", ...variables, signal });

/**
 * Get current user profile
 */
export function userControllerGetCurrentUserQuery(
  variables: UserControllerGetCurrentUserVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<undefined>;
};

export function userControllerGetCurrentUserQuery(
  variables: UserControllerGetCurrentUserVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<undefined>)
    | reactQuery.SkipToken;
};

export function userControllerGetCurrentUserQuery(
  variables: UserControllerGetCurrentUserVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/user",
      operationId: "userControllerGetCurrentUser",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchUserControllerGetCurrentUser(variables, signal),
  };
}

/**
 * Get current user profile
 */
export const useSuspenseUserControllerGetCurrentUser = <TData = undefined>(
  variables: UserControllerGetCurrentUserVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      undefined,
      UserControllerGetCurrentUserError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useNeurachatContext(options);
  return reactQuery.useSuspenseQuery<
    undefined,
    UserControllerGetCurrentUserError,
    TData
  >({
    ...userControllerGetCurrentUserQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * Get current user profile
 */
export const useUserControllerGetCurrentUser = <TData = undefined>(
  variables: UserControllerGetCurrentUserVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      undefined,
      UserControllerGetCurrentUserError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useNeurachatContext(options);
  return reactQuery.useQuery<
    undefined,
    UserControllerGetCurrentUserError,
    TData
  >({
    ...userControllerGetCurrentUserQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type UserControllerUpdateUserProfileError =
  Fetcher.ErrorWrapper<undefined>;

export type UserControllerUpdateUserProfileVariables = {
  body?: Schemas.UpdateUserRequest;
} & NeurachatContext["fetcherOptions"];

export const fetchUserControllerUpdateUserProfile = (
  variables: UserControllerUpdateUserProfileVariables,
  signal?: AbortSignal,
) =>
  neurachatFetch<
    undefined,
    UserControllerUpdateUserProfileError,
    Schemas.UpdateUserRequest,
    {},
    {},
    {}
  >({ url: "/user", method: "put", ...variables, signal });

export const useUserControllerUpdateUserProfile = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      UserControllerUpdateUserProfileError,
      UserControllerUpdateUserProfileVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useNeurachatContext();
  return reactQuery.useMutation<
    undefined,
    UserControllerUpdateUserProfileError,
    UserControllerUpdateUserProfileVariables
  >({
    mutationFn: (variables: UserControllerUpdateUserProfileVariables) =>
      fetchUserControllerUpdateUserProfile(
        deepMerge(fetcherOptions, variables),
      ),
    ...options,
  });
};

export type UserControllerChangeUserPasswordError =
  Fetcher.ErrorWrapper<undefined>;

export type UserControllerChangeUserPasswordVariables =
  NeurachatContext["fetcherOptions"];

export const fetchUserControllerChangeUserPassword = (
  variables: UserControllerChangeUserPasswordVariables,
  signal?: AbortSignal,
) =>
  neurachatFetch<
    undefined,
    UserControllerChangeUserPasswordError,
    undefined,
    {},
    {},
    {}
  >({ url: "/user/password", method: "patch", ...variables, signal });

export const useUserControllerChangeUserPassword = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      UserControllerChangeUserPasswordError,
      UserControllerChangeUserPasswordVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useNeurachatContext();
  return reactQuery.useMutation<
    undefined,
    UserControllerChangeUserPasswordError,
    UserControllerChangeUserPasswordVariables
  >({
    mutationFn: (variables: UserControllerChangeUserPasswordVariables) =>
      fetchUserControllerChangeUserPassword(
        deepMerge(fetcherOptions, variables),
      ),
    ...options,
  });
};

export type QueryOperation =
  | {
      path: "/health-check";
      operationId: "appControllerGetHealthCheck";
      variables: AppControllerGetHealthCheckVariables | reactQuery.SkipToken;
    }
  | {
      path: "/";
      operationId: "appControllerGetRoot";
      variables: AppControllerGetRootVariables | reactQuery.SkipToken;
    }
  | {
      path: "/auth/confirm-email/{token}";
      operationId: "authControllerConfirmEmail";
      variables: AuthControllerConfirmEmailVariables | reactQuery.SkipToken;
    }
  | {
      path: "/utils/username/{username}";
      operationId: "utilsControllerCheckUsernameUniqueness";
      variables:
        | UtilsControllerCheckUsernameUniquenessVariables
        | reactQuery.SkipToken;
    }
  | {
      path: "/user";
      operationId: "userControllerGetCurrentUser";
      variables: UserControllerGetCurrentUserVariables | reactQuery.SkipToken;
    };
