/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type NoResponseDataDto = {
  /**
   * Response status
   *
   * @example success
   */
  status: "success";
  /**
   * Response message
   *
   * @example OTP resent successfully
   */
  message: string;
  /**
   * Response timestamp
   *
   * @example 2024-01-01T00:00:00.000Z
   */
  timestamp: string;
};

export type RegisterRequest = {
  /**
   * User email
   *
   * @example user@example.com
   */
  email: string;
  /**
   * Password for the user account
   *
   * @example pa@$W0rD
   */
  password: string;
  /**
   * User username
   *
   * @example username123
   */
  username: string;
};

export type ExceptionPayloadDto = {
  /**
   * Error messages
   */
  messages: string[];
};

export type ExceptionDto = {
  /**
   * Response status
   *
   * @example error
   */
  status: "error";
  /**
   * Response message
   *
   * @example Bad Request Exception
   */
  message: string;
  /**
   * Response data containing error messages
   *
   * @example {"messages":["A sample error","Lorem ipsum error"]}
   */
  data?: ExceptionPayloadDto;
  /**
   * Response timestamp
   *
   * @example 2024-01-01T00:00:00.000Z
   */
  timestamp: string;
};

export type LoginRequest = {
  /**
   * Username or email of the user being authenticated
   *
   * @example RandomUsernameOrEmail
   */
  usernameOrEmail: string;
  /**
   * Password of the user being authenticated
   *
   * @example RandomPassword
   */
  password: string;
};

export type UserResponse = {
  /**
   * User id
   *
   * @example 1
   */
  id: number;
  /**
   * User email
   *
   * @example user@example.com
   */
  email: string;
  /**
   * User username
   *
   * @example username123
   */
  username: string;
  /**
   * User creation time
   *
   * @example 2024-01-01T00:00:00.000Z
   */
  createdAt: string;
  /**
   * Last update time
   *
   * @example 2024-01-01T01:00:00.000Z
   */
  updatedAt: string;
  /**
   * Avatar URL
   *
   * @example https://example.com/avatar.png
   */
  avatarUrl?: string | null;
  /**
   * Account status
   *
   * @example verified
   */
  status: "verified" | "unverified" | "locked";
};

export type TokensResponse = {
  /**
   * JWT access token
   *
   * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
   */
  accessToken: string;
};

export type LoginResponse = {
  user: UserResponse;
  tokens: TokensResponse;
};

export type ForgotPasswordRequest = {
  /**
   * Email address of the user being authenticated
   *
   * @example johndoe@example.com
   */
  email: string;
};

export type ResetPasswordRequest = {
  /**
   * Password for the user account
   *
   * @example pa@$W0rD
   */
  password: string;
  /**
   * Password confirmation
   *
   * @example pa@$W0rD
   */
  confirmPassword: string;
  /**
   * Email address of the user being authenticated
   *
   * @example johndoe@example.com
   */
  email: string;
  /**
   * Reset token sent to the user's email
   *
   * @example random token
   */
  token: string;
};
